### PR TITLE
Add Go->Gno bytebeat workshop

### PR DESCRIPTION
**Pull request by schollz**
@michelleellen Here are all the resources from my workshop, all the source files are here along with a finalized PDF.

### CODE REVIEW

**Comment by michelleellen** [comment]
Here is the recording https://www.youtube.com/watch?v=lmmUIEHhdqA

**Comment by roethke** [comment]
@michelleellen What is the action item here with regards to assigning us on this issue: is it for review or is there something else needed from us?

**Comment by michelleellen** [comment]
@waymobetta I am not sure if you saw my Signal message about this, but I don't want to merge a pull request without a secondary review.

**Comment by roethke** [comment]
@michelleellen Sounds good. In the future, if you're looking for review you can select us from the review dropdown. Do you have permissions to do this?

Screenshot 2023-10-17 at 11 41 26 AM

**Review by moul — APPROVED** [review]

**Pull request merged**
